#卖出物品时 价格下降的比例
Sell:
    #表示物品ID为1 损伤值为任意值的物品 0.01表示1%
    #表示物品ID为4 损伤值为0的物品 
    - '1:*|0.01'
    - '4:0|0.01'
#设定同类物品 同一组的为同一类
#&后面表示权重
#1:*&2表示物品ID为1的所有物品 它在这个类里的权重为2
Class:
    - '1:*&2,2:*&2,3:*&6'